version: 2
builds:
  - main: ./app.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-ldflags '{{.Env.VERSION_BUILD_FLAG}}'"
build:
  # Configuration for the build process
  hooks:
    pre:
      # Commands to run before building
      - make init
    post:
      # Commands to run after building
      - echo "Build completed"
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: prasunanand
    name: zasper
    prerelease: true
