version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./app.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags: "-ldflags '{{.Env.VERSION_BUILD_FLAG}}'"
    hooks:
      pre:
        - make init
      post:
        - echo "Build completed"
checksum:
  name_template: 'checksums.txt'
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: prasunanand
    name: zasper
