version: 2
builds:
  - main: ./app.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-ldflags '{{.Env.VERSION_BUILD_FLAG}}'"
    hooks:
      pre:
        - make init
      post:
        - echo "Build completed"
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: prasunanand
    name: zasper
    draft: false
