version: 2
builds:
  - main: ./app.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
dockers:
  - image: "ghcr.io/prasunanand/zasper:{{ .Version }}"
    dockerfile: Dockerfile
release:
  github:
    owner: prasunanand
    name: zasper
    prerelease: true
