name: zasper
base: core22
version: '0.1.0-beta'
summary: High Performance IDE for Jupyter Notebooks
description: |
  Zasper is a High Performance IDE for Jupyter Notebooks.

grade: stable
confinement: strict

apps:
  zasper:
    command: bin/zasper
    plugs:
      - network
      - network-bind
      - home

parts:
  zasper:
    plugin: nil
    source: .
    build-packages:
      - make
      - gcc
      - golang-go
      - curl
      - gnupg
    override-build: |
      # Install Node.js 20.x
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get update
      apt-get install -y nodejs curl gnupg make gcc

      # Remove old golang-go
      apt-get remove -y golang-go || true

      ARCH=$(dpkg --print-architecture)
      case "$ARCH" in
        amd64)
          GO_TAR=go1.23.2.linux-amd64.tar.gz
          ;;
        arm64)
          GO_TAR=go1.23.2.linux-arm64.tar.gz
          ;;
        ppc64el)
          GO_TAR=go1.23.2.linux-ppc64le.tar.gz
          ;;
        s390x)
          GO_TAR=go1.23.2.linux-s390x.tar.gz
          ;;
        riscv64)
          GO_TAR=go1.23.2.linux-riscv64.tar.gz
          ;;
        armhf)
          GO_TAR=go1.23.2.linux-armv6l.tar.gz  # closest for armhf
          ;;
        *)
          echo "Unsupported architecture $ARCH"
          exit 1
          ;;
      esac

      curl -L -O https://go.dev/dl/$GO_TAR
      rm -rf /usr/local/go
      tar -C /usr/local -xzf $GO_TAR
      export PATH=/usr/local/go/bin:$PATH
      go version

      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      # Build steps
      make init
      make build
      ls -l

      # Install binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp zasper $SNAPCRAFT_PART_INSTALL/bin/
      ls -l $SNAPCRAFT_PART_INSTALL/bin
