name: Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-go:
    name: Build and Release Go Binary with GoReleaser
    runs-on: ubuntu-latest
    env:
      MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
      MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
      MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
      MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
      MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      VERSION_BUILD_FLAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.7'

      - name: Build and Release Go Binary with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
